# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vavido_code/rv32i_v1/rv32i_v0.srcs/sources_1/ip/irom_test/irom_test.xci
# IP: The module: 'irom_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vavido_code/rv32i_v1/rv32i_v0.gen/sources_1/ip/irom_test/irom_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom_test'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vavido_code/rv32i_v1/rv32i_v0.srcs/sources_1/ip/irom_test/irom_test.xci
# IP: The module: 'irom_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vavido_code/rv32i_v1/rv32i_v0.gen/sources_1/ip/irom_test/irom_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
