# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado_code/rv32i_v0/rv32i_v0.srcs/sources_1/ip/ram8x4/ram8x4.xci
# IP: The module: 'ram8x4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_code/rv32i_v0/rv32i_v0.gen/sources_1/ip/ram8x4/ram8x4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram8x4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Vivado_code/rv32i_v0/rv32i_v0.srcs/sources_1/ip/ram8x4/ram8x4.xci
# IP: The module: 'ram8x4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_code/rv32i_v0/rv32i_v0.gen/sources_1/ip/ram8x4/ram8x4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram8x4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
